[tool.poetry]
name = "mcp_change_analyzer"
version = "0.1.0"
description = "Git Change Analyzer MCP Server with A2A Protocol Support"
authors = ["Manav Gupta <manavg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastmcp = "^0.1.0"
pydantic = "^2.0.0"
gitpython = "^3.1.30"
fastapi = ">=0.100.0"
uvicorn = ">=0.22.0"
httpx = ">=0.26.0"
mcp-shared-lib = { path = "../mcp_shared_lib", develop = true }

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
flake8 = "^6.0.0"
mypy = "^1.3.0"
isort = "^5.12.0"

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
